#define WORDCOUNT 117
#define SUPERWORDCOUNT 3

int HangmanWordLists[SKILLCOUNT][WORDCOUNT] = 
{
    {
        "above", "accounts", "afford", "alive", "alive", "ant", "awesome", "ball",
        "balloon", "below", "bishop", "bordering", "bowling", "bullshit", "burn", "buzzes",
        "cancels", "cannon", "chain", "chewing", "clung", "dancer", "desirable", "dine",
        "dish", "doom", "dream", "driving", "eagle", "escape", "everything", "fixes",
        "ghost", "glowing", "gray", "haunt", "heavy", "hooked", "hotter", "hummed",
        "hurry", "incompetence", "intellect", "invest", "jewel", "king", "laser", "leave",
        "lightly", "listened", "logic", "lotion", "magazine", "member", "messy", "metal",
        "mummy", "nearby", "none", "oatmeal", "over", "pears", "perverted", "play",
        "popped", "potato", "power", "pretend", "provides", "quack", "quest", "radio",
        "rider", "robbery", "rotating", "shaped", "simple", "skull", "skunks", "slaves",
        "smartass", "southwest", "steam", "stickers", "strangers", "subtraction", "suffering", "swan",
        "tag", "taker", "tasked", "tickle", "tomato", "train", "tumble", "vanish",
        "vocabulary", "wake", "wood", "words", "worm", "yellow", "above", "accounts",
        "afford", "alive", "alive", "ant", "awesome", "ball", "balloon", "below",
        "bishop", "bordering", "bowling", "bullshit", "burn", 
    },

    {
        "advantages", "aerial", "alternative", "america", "antonym", "aquatic", "average", "baseballs",
        "battlegrounds", "bombardment", "boon", "boundless", "canals", "cancer", "cartridges", "chocolate",
        "cistern", "civilized", "comical", "commends", "construction", "crazy", "decays", "decomposing",
        "degenerated", "demonstrated", "destruction", "dew", "diamond", "diversity", "draining", "dropper",
        "egyptian", "entered", "errors", "evidently", "exceed", "existed", "exploit", "extensively",
        "fascinating", "frontal", "gaping", "garner", "gashes", "geyser", "gunpowder", "haircut",
        "highlander", "hotshot", "imprisoning", "inattention", "infamous", "infinite", "insane", "insurance",
        "invest", "investigative", "invisible", "keeper", "kicker", "lackluster", "lapse", "leggings",
        "matches", "mechanical", "meekly", "mellowing", "metaphorically", "metro", "monumental", "motherly",
        "naughtiness", "notch", "obscene", "obscure", "onrush", "pamper", "paperwork", "perishing",
        "photographed", "pleaded", "porcupine", "porpoise", "possible", "previewed", "propels", "redistribute",
        "reflexive", "representation", "resulted", "rhyming", "rhythm", "ruse", "salvage", "selection",
        "slicks", "smithereens", "snugly", "stepmother", "storminess", "suffocate", "synonym", "tasteless",
        "thoughtlessness", "totalling", "transmitter", "tree", "trustworthy", "unaffected", "unbelievable", "unholy",
        "uniquely", "voluntarily", "weasels", "whiff", "wincing", 
    },

    {
        "Poseidon", "abrasions", "adages", "aggregate", "aghast", "aids", "alienates", "allays",
        "anglican", "annihilation", "apparitions", "aqueous", "archaic", "barkeep", "befallen", "befuddle",
        "belligerent", "bifocals", "bolster", "bombastic", "brazen", "brevity", "ceasing", "celibacy",
        "cliques", "coinciding", "conceivable", "conductive", "consolers", "covetous", "crimson", "custodial",
        "dehumanization", "delineate", "delirium", "dicky", "discrepant", "distilling", "dogtooth", "enveloped",
        "excruciating", "expeditious", "facet", "fatigues", "gargoyle", "geochemistry", "googol", "granularity",
        "illogically", "incentive", "ineffable", "inscrutable", "intimacy", "itemizing", "lacerates", "lackluster",
        "lampoon", "limelight", "logistic", "luscious", "lusciousness", "magnifier", "maternity", "multitask",
        "muse", "nailgun", "nihilism", "node", "objective", "obscurities", "obsidian", "osmosis",
        "panacea", "paternity", "pedantic", "periphery", "philanthropy", "polearm", "prevalence", "prudent",
        "pulverization", "quake", "queued", "ranger", "renaissance", "retinal", "sacking", "sanctimonious",
        "scimitar", "seismology", "silt", "simplicity", "skirmish", "sputter", "subjective", "sullenness",
        "supplicate", "surreal", "synagogue", "tapestries", "tempter", "tenements", "tribunals", "trite",
        "typeface", "veracity", "wiretapping", "wreak", "Poseidon", "abrasions", "adages", "aggregate",
        "aghast", "aids", "alienates", "allays", "anglican", 
    },

    {
        "abjudicate", "acerbic", "acrimony", "aerobacter", "aeronautics", "algol", "anisotropic", "aphorism",
        "apocryphal", "arrogation", "auk", "benighted", "besmirches", "betrothal", "bifurcate", "bittern",
        "capricious", "chicanery", "coccidiosis", "contiguous", "corer", "creedal", "cyanate", "cysteine",
        "demagogue", "deuterium", "disengenious", "dissension", "eddies", "efficacy", "eloquence", "equivocate",
        "ermines", "etymology", "euclidian", "euthanasia", "forbearance", "fourier", "frustum", "germination",
        "halcyon", "heterozygous", "hierarchy", "histogram", "hyperbola", "iconoclast", "improvident", "jasper",
        "layby", "lexicon", "logomachy", "loquacious", "luge", "lynx", "metaclassing", "metamorphic",
        "milieu", "modularity", "myeloid", "myopic", "nape", "neurological", "nootropic", "obviate",
        "oncology", "outlays", "palatine", "pasteup", "pauldron", "peccary", "pecuniary", "peepy",
        "phylactery", "phytoplankton", "pillory", "proclivity", "procyon", "puerile", "pusillanimous", "quintic",
        "rawboned", "renege", "reticent", "rhombi", "ribosome", "schizoid", "scintilla", "sojourn",
        "spectrograph", "spikenard", "stroboscopic", "syllogism", "syndic", "tamarind", "tappet", "tautological",
        "teetotal", "terminus", "triatomic", "ubiquitous", "vilify", "virtuosity", "vitiate", "winningly",
        "abjudicate", "acerbic", "acrimony", "aerobacter", "aeronautics", "algol", "anisotropic", "aphorism",
        "apocryphal", "arrogation", "auk", "benighted", "besmirches", 
    },

    {
        "ablutomania", "absquatulate", "anautarchia", "baffona", "bradykinin", "canto", "dactylion", "delicti",
        "eccedentesiast", "erinaceous", "fabiform", "gabelle", "hyoid", "iodate", "jentacular", "jobbernowl",
        "kazatzka", "knismesis", "lexiphanic", "lipschitz", "matins", "matriculate", "necrotype", "orgulous",
        "pauciloquent", "philosophaster", "plenipotentiary", "pyknic", "pyx", "qua", "quipu", "quodlibet",
        "scacchic", "thob", "tittynope", "tyromancy", "varsovienne", "winklepicker", "wyn", "xanthic",
        "xylophilous", "yarborough", "yclept", "yestreen", "zenzizenzizenzic", "zoanthropy", "zoppetto", "ablutomania",
        "absquatulate", "anautarchia", "baffona", "bradykinin", "canto", "dactylion", "delicti", "eccedentesiast",
        "erinaceous", "fabiform", "gabelle", "hyoid", "iodate", "jentacular", "jobbernowl", "kazatzka",
        "knismesis", "lexiphanic", "lipschitz", "matins", "matriculate", "necrotype", "orgulous", "pauciloquent",
        "philosophaster", "plenipotentiary", "pyknic", "pyx", "qua", "quipu", "quodlibet", "scacchic",
        "thob", "tittynope", "tyromancy", "varsovienne", "winklepicker", "wyn", "xanthic", "xylophilous",
        "yarborough", "yclept", "yestreen", "zenzizenzizenzic", "zoanthropy", "zoppetto", "ablutomania", "absquatulate",
        "anautarchia", "baffona", "bradykinin", "canto", "dactylion", "delicti", "eccedentesiast", "erinaceous",
        "fabiform", "gabelle", "hyoid", "iodate", "jentacular", "jobbernowl", "kazatzka", "knismesis",
        "lexiphanic", "lipschitz", "matins", "matriculate", "necrotype", 
    },
};

int HangmanSuperWords[SUPERWORDCOUNT] = 
{
    "bird", "internet", "lol", 
};
